services:
  hub:
    image: selenium/hub:4.23.0
    ports:
    - 4444:4444
 #   - 4442:4442
 #   - 4443:4443
  chrome:
    image: selenium/node-chrome
    shm_size: 2gb 
    depends_on:
      - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSION=true
    - SE_NODE_MAX_SESSIONS=4
    - SE_VNC_NO_PASSWORD=1
  firefox:
     image: selenium/node-firefox
     shm_size: 2gb
     depends_on:
       - hub
     environment:
     - SE_EVENT_BUS_HOST=hub
     - SE_EVENT_BUS_PUBLISH_PORT=4442
     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
     - SE_NODE_OVERRIDE_MAX_SESSION=true
     - SE_NODE_MAX_SESSIONS=4
     - SE_VNC_NO_PASSWORD=1
  signup-suite:
    image: javierol97/selenium-grid-docker
    depends_on:
     - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=2
    - TEST_SUITE=signup-test.xml
    volumes:
    - ./output/signup-test:/home/selenium-docker/test-output



