services:
  hub:
    image: selenium/hub:4.23.0
  chrome:
    image: selenium/node-chrome
    shm_size: 2gb 
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file: .env
  firefox:
     image: selenium/node-firefox
     shm_size: 2gb
     depends_on:
      - hub
     deploy:
      replicas: 1
     env_file: .env



