services:
  suite:
    image: javierol97/selenium-grid-docker
    environment:
    - BROWSER
    - HUB_HOST=hub
    - THREAD_COUNT
    - TEST_SUITE=${TEST_SUITE}.xml
    volumes:
    - ./output/${TEST_SUITE}:/home/selenium-docker/test-output


